services:
  db:
    image: postgres:16
    container_name: tutor_db
    restart: always
    environment:
      POSTGRES_DB: Tutor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1  # В продакшене замените на секрет
    ports:
      - "5432:5432"
    volumes:
      - tutor_db_data:/var/lib/postgresql/data
    networks:
      - tutor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: tutor_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - db
    networks:
      - tutor_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutor_app
    depends_on:
      - db
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Tutor;Username=postgres;Password=1
      - Kafka__BootstrapServers=kafka:9092
      - EmailSettings__SmtpServer=smtp.yandex.ru
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUser=vyacheslav.gvozdikov@yandex.ru
      - EmailSettings__SmtpPass=${SMTP_PASSWORD}
      - EmailSettings__FromEmail=vyacheslav.gvozdikov@yandex.ru
      - EmailSettings__FromName=Tutor Service
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - tutor_network

networks:
  tutor_network:

volumes:
  tutor_db_data: